<?php
/**
 * Created by PhpStorm.
 * User: erik
 * Date: 20-12-17
 * Time: 17:39
 */

class CRM_Invoicestoexact_Form_Task_InvoiceExact extends CRM_Contribute_Form_Task {

  function preProcess() {
    CRM_Core_Error::debug('task', $this);
    exit();
    parent::preProcess(); // TODO: Change the autogenerated stub
  }


}